# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/19324f88-fbf3-41a8-8758-1c35604d7137";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EF5B-1A82";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/d76ba515-91c4-4316-97ca-749ad2e4e22f";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;


  # Added boot parameters for ACPI and hardware support
# boot.kernelParams = [
#    "acpi_osi=Linux"
#    "acpi_osi=!Windows 2020"
#    "acpi.debug_layer=0"
#    "acpi.debug_level=0"
#    "pcie_aspm=off"
#    "nvidia-drm.modeset=1"
#  ];

  # Modified kernel modules for proper hardware support
# boot.initrd.availableKernelModules = [ 
#    "xhci_pci" 
#    "ahci" 
#    "nvme" 
#    "usb_storage" 
#    "sd_mod" 
#    "sdhci_pci"
#    "nvidia" 
#    "nvidia_modeset"
#    "nvidia_uvm"
#   "nvidia_drm"
#  ];
#
}
