# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Base kernel modules as detected by nixos-generate-config
  boot.initrd.availableKernelModules = [
    # Base system modules
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
    # Additional hardware support
    "thinkpad_acpi"
    "coretemp"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # NVIDIA modules are handled by the nvidia-specific configuration
  hardware.nvidia = {
    package = config.boot.kernelPackages.nvidiaPackages.stable;
    modesetting.enable = true;
  };

  # Kernel parameters moved to configuration.nix to avoid conflicts
  # All kernel parameters are now centrally managed in configuration.nix
  # using lib.mkForce to override any conflicting parameters from modules

  # Filesystem configuration
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/19324f88-fbf3-41a8-8758-1c35604d7137";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EF5B-1A82";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/d76ba515-91c4-4316-97ca-749ad2e4e22f";
    fsType = "ext4";
  };

  # Temporary build directory with more space
  fileSystems."/tmp/nix-build" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [ "size=10G" ];
  };
  
  
  # ===== CUSTOM DATA DRIVE MOUNTS =====
  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/6e893b17-365c-49bb-940e-767b32712eb2";
    fsType = "ext4";
    options = [ "defaults" "noatime" ];
  };

  fileSystems."/var/lib/docker" = {
    device = "/dev/disk/by-uuid/ae7f3150-5c3e-4890-8ae2-2adcc684d45f";
    fsType = "ext4";
  };

  fileSystems."/mnt/storage" = {
    device = "/dev/disk/by-uuid/e74a23d2-545e-47e4-a673-e464a99eb46b";
    fsType = "ext4";
    options = [ "defaults" "noatime" ];
  };




  swapDevices = [ ];

  # Network configuration
  networking.useDHCP = lib.mkDefault true;

  # Platform configuration
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
